"""empty message

Revision ID: 249dd66ccc80
Revises: 62d15182c4ea
Create Date: 2022-08-11 23:15:33.253365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249dd66ccc80'
down_revision = '62d15182c4ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('genres', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'genres')
    # ### end Alembic commands ###
