"""empty message

Revision ID: 62d15182c4ea
Revises: fdd2faa936d1
Create Date: 2022-08-11 16:47:10.654180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62d15182c4ea'
down_revision = 'fdd2faa936d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_time', sa.Date(), nullable=True))
    op.add_column('venues', sa.Column('website', sa.String(length=250), nullable=True))
    op.add_column('venues', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('venues', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'description')
    op.drop_column('venues', 'seeking_talent')
    op.drop_column('venues', 'website')
    op.drop_column('shows', 'start_time')
    # ### end Alembic commands ###
